apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/dbritto-dev/nd064_capstone_starter
    targetRevision: HEAD
    path: kubernetes-manifests/dev
